#!/usr/bin/env bash
# Acquire documentation sources for meshimize-provider groups.
# Usage: ./scripts/acquire-docs.sh [slug]
# If slug is provided, only acquire that group's docs.
# If no slug, acquire all configured groups.

set -euo pipefail

DOCS_DIR="./docs-source"

# ─── Fly.io Docs ───
acquire_fly_docs() {
  local slug="fly-docs"
  local repo="https://github.com/superfly/docs.git"
  local target="${DOCS_DIR}/${slug}"

  if [ -d "${target}/.git" ]; then
    echo "Updating ${slug}..."
    git -C "${target}" pull --ff-only
  else
    echo "Cloning ${slug}..."
    mkdir -p "${DOCS_DIR}"
    git clone --depth 1 "${repo}" "${target}"
  fi

  echo "Acquired: ${slug} → ${target}"
}

# ─── Elixir Docs ───
# Builds Elixir standard library docs from source using ExDoc.
# Prerequisites: Erlang/OTP 27+, git, make, mix (from Erlang install)
acquire_elixir_docs() {
  local slug="elixir-docs"
  local elixir_version="${ELIXIR_VERSION:-v1.18.3}"
  local target="${DOCS_DIR}/${slug}"
  local work_dir="${DOCS_DIR}/.elixir-build"
  local elixir_repo="https://github.com/elixir-lang/elixir.git"
  local ex_doc_repo="https://github.com/elixir-lang/ex_doc.git"

  echo "Building Elixir docs from source (${elixir_version})..."
  echo "  This requires Erlang/OTP 27+ and takes several minutes."

  # Verify Erlang is available
  if ! command -v erl &>/dev/null; then
    echo "ERROR: Erlang/OTP not found. Install Erlang/OTP 27+ first." >&2
    exit 1
  fi

  # Set up working directory
  mkdir -p "${work_dir}"

  local elixir_dir="${work_dir}/elixir"
  local ex_doc_dir="${work_dir}/ex_doc"

  # Clone or update Elixir repo at specified version
  if [ -d "${elixir_dir}/.git" ]; then
    echo "Updating Elixir repo..."
    git -C "${elixir_dir}" fetch --tags
    git -C "${elixir_dir}" checkout "${elixir_version}"
    git -C "${elixir_dir}" clean -fdx
  else
    echo "Cloning Elixir repo (${elixir_version})..."
    git clone "${elixir_repo}" "${elixir_dir}"
    git -C "${elixir_dir}" checkout "${elixir_version}"
  fi

  # Clone or update ExDoc as sibling directory
  if [ -d "${ex_doc_dir}/.git" ]; then
    echo "Updating ExDoc repo..."
    git -C "${ex_doc_dir}" pull --ff-only
  else
    echo "Cloning ExDoc..."
    git clone --depth 1 "${ex_doc_repo}" "${ex_doc_dir}"
  fi

  # Compile Elixir from source
  echo "Compiling Elixir from source..."
  make -C "${elixir_dir}" clean compile

  # Build ExDoc escript
  echo "Building ExDoc..."
  (
    cd "${ex_doc_dir}"
    export PATH="${elixir_dir}/bin:${PATH}"
    mix local.hex --force --if-missing
    mix deps.get
    mix compile
    mix escript.build
  )

  # Generate docs with ExDoc markdown output
  echo "Generating Elixir docs..."
  (
    cd "${elixir_dir}"
    export PATH="${elixir_dir}/bin:${PATH}"
    make docs
  )

  # Clean and populate target directory (idempotent)
  echo "Copying docs to ${target}..."
  rm -rf "${target}"
  mkdir -p "${target}"

  # Copy the 6 doc sets (generated by ExDoc)
  local doc_sets=("elixir" "mix" "ex_unit" "iex" "logger" "eex")
  for doc_set in "${doc_sets[@]}"; do
    local src="${elixir_dir}/doc/${doc_set}"
    if [ -d "${src}" ]; then
      cp -r "${src}" "${target}/${doc_set}"
      echo "  Copied: doc/${doc_set}/"
    else
      echo "  WARNING: doc/${doc_set}/ not found, skipping"
    fi
  done

  # Copy guide pages from lib/elixir/pages/
  local pages_dir="${elixir_dir}/lib/elixir/pages"
  if [ -d "${pages_dir}" ]; then
    mkdir -p "${target}/guides"
    find "${pages_dir}" -name '*.md' -exec cp {} "${target}/guides/" \;
    local guide_count
    guide_count=$(find "${target}/guides" -name '*.md' | wc -l | tr -d ' ')
    echo "  Copied: ${guide_count} guide pages"
  else
    echo "  WARNING: lib/elixir/pages/ not found, skipping guides"
  fi

  echo "Acquired: ${slug} → ${target}"
}

# ─── Main ───
case "${1:-all}" in
  fly-docs) acquire_fly_docs ;;
  elixir-docs) acquire_elixir_docs ;;
  all)
    acquire_fly_docs
    acquire_elixir_docs
    ;;
  *) echo "Unknown slug: $1"; exit 1 ;;
esac
